### ISSUE TITLE
LEAK

### ISSUE THREAD

**Issue by PakitoSec** [Movilizer/mvz-java-sdk#1]
Bonjour,

Pouvez-vous enlever toute référence au mot clé ENEDIS ?

-#erdf.consultationmesures.endpoint=http://localhost:8080/ekwadif-webservice-mock/ConsultationMesures
-erdf.consultationmesures.endpoint=https://sge-b2b.enedis.fr/ConsultationMesures/v1.0
-erdf.recherchePoint.version=1.0
-erdf.recherchePoint.endpoint=https://sge-b2b.enedis.fr/RecherchePoint/v1.0
-erdf.commandesouscription.version=1.0
-erdf.commandesouscription.endpoint=http://localhost:8080/ekwadif-webservice-mock/CommandeSouscription
-erdf.changementfournisseurf130b1.version=6.0

Cordialement,

**Comment by cyrilJoul** [comment]
Hello, a DMCA request has discard the whole litigious repository. i let you edit your comment to exclude the lasts references. Cyril
